# Generated by Django 5.0.7 on 2024-07-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_productrating_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='reviews',
            field=models.TextField(default=None),
        ),
    ]
